sudo: required
dist: trusty
addons:
  chrome: stable
language: node_js
git:
  depth: 3
node_js:
  - "8"
install:
  - bundle install
  - npm install
script:
  - npm run deploy
cache:
  directories:
    - node_modules
    - vendor/bundle
